### ISSUE TITLE
skimage cannot be imported

### ISSUE THREAD

**Issue by kmader** [Kaggle/docker-python#103]
When running 
```from skimage.util.montage import montage2d``` the following error gets thrown in the log file
```
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```

**Comment by nerdcha** [comment]
Thanks for reporting this! Looks like we might have been hit by https://github.com/ContinuumIO/anaconda-issues/issues/720 . I'll try the fix suggested there and see how we go.

**Comment by nerdcha** [comment]
Sorry for the delay in patching this. I think that https://github.com/Kaggle/docker-python/commit/0cb6792a9733bdb9cffcd822e671f568e674a0cd fixed it. Apologies for the inconvenience, and do let us know if you hit any more issues!

**Comment by nerdcha** [comment]
Oh, shoot. Thanks for the report @hyzhak, and for the hint about numpy. I'll get this patched asap.

**Comment by nerdcha** [comment]
We've deployed your [hotfix](https://github.com/Kaggle/docker-python/commit/d32fda296ef8538764728309e5bdd16f61481a38), @hyzhak, and `from skimage.io import imread` is working once more. Thanks again for the superlatively helpful bug report!

**Comment by SanketBadhe** [comment]
I tried all above solution but still, I am getting same issue.

**Comment by inakicm** [comment]
It seems that this issue is back

`from skimage.util.montage import montage2d as montage`
generates this error:
`ModuleNotFoundError: No module named 'skimage.util.montage'`

**Comment by anoop93** [comment]
@inakicm  try this...
from skimage.util import montage2d as montage

**Comment by aysenozun** [comment]
Probably your doesnt support 2d computer .
from skimage.util import montage

**Comment by mrgransky** [comment]
You may want to try this piece of code:
```
try:
    from skimage.util.montage import montage2d
except ImportError as e:
    print('scikit-image is too new, ',e)
    from skimage.util import montage as montage2d
```

**Comment by oldmoon0224** [comment]
try 
`from skimage.util import montage as montage2d`
