### ISSUE TITLE
geopandas failing import - maybe because Dockerfile is importing fiona before geopandas

### ISSUE THREAD

**Issue by MaryLvV** [Kaggle/docker-python#227]
<img width="735" alt="screen shot 2018-07-01 at 6 52 58 am" src="https://user-images.githubusercontent.com/8145655/42134150-94d5e99e-7cfb-11e8-8a77-edc13d0a3880.png">
<img width="1264" alt="screen shot 2018-07-01 at 6 53 13 am" src="https://user-images.githubusercontent.com/8145655/42134151-96e622f8-7cfb-11e8-9d65-93c0a4587a85.png">

**Comment by yurigabrich** [comment]
Hi!
We've been [discussing this issue on kaggle](https://www.kaggle.com/product-feedback/60653#post353813) too.

Looks like there are version conflicts. If you have docker images from before June, you can use it for a temporary fix.

**Comment by crawforc3** [comment]
Fixed :)

https://www.kaggle.com/crawford/geopandas-test

**Comment by pavankumarkulkarni** [comment]
Hi,

Still getting the error on geopandas import command. screenshot of my kernel execution error message.
please help

![geopandas error](https://user-images.githubusercontent.com/10427824/48264377-493d9500-e3f7-11e8-82b8-d4a6ecdc7015.png)
