### ISSUE TITLE
SimpleITK?

### ISSUE THREAD

**Issue by kmader** [Kaggle/docker-python#57]
For the 2017 Kaggle Data Science Bowl the tutorial (https://github.com/booz-allen-hamilton/DSB3Tutorial) uses the SimpleITK package for loading and processing DICOMS a tool that is much better suited than pydicom for 3D data.  Can this be added to the Docker Image / Kernels?

**Comment by nerdcha** [comment]
Resolved in https://github.com/Kaggle/docker-python/pull/58

**Comment by kmader** [comment]
This isn't resolved any more, it has been removed
![image](https://cloud.githubusercontent.com/assets/116120/25169196/682ae53e-24e6-11e7-9110-fdbd96666265.png)

**Comment by nerdcha** [comment]
Thanks for the nudge. Looks like v1.0.0 of SimpleITK now supports Python 3.6. I'll add that to the image and deploy it shortly.
